version: '3'
services:

  nginx:
    image: nginx:alpine
    container_name: production_nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./build:/static
    ports:
    - 8080:80
    - 443:443
    links:
    - web:app
  web:
    env_file:
      - .env
    image: 'minesweeper:v1'
    container_name: app
    environment:
    - REDIS_HOST=${REDIS_HOST}
    links:
    - redis:redis
  redis:
    container_name: 'redis'
    image: "redis:alpine"
    ports:
    - 6379:6379
    command: "redis-server --appendonly yes"
    volumes:
    - ./data:/data

